title:        Chris Burnell
short_title:  cb
tagline:      'Iâ€™m Ravenous for CSS.'
lede:         'Iâ€™m a <span class="canada">Canadian</span> UI developer living in London, UK. This is where I write about and share my passions: CSS, best practices and standards, web performance, front-end development, innovations on the web, sharing knowledge, and owning your content.'
color:        5f8aa6
color_scheme: false

author:
  name:        Chris Burnell
  nationality: Canadian
  location:    London, UK
  email:       me@chrisburnell.com
  role:        UI Developer
  pgp:         9604F098260A0057
  codepen:     chrisburnell
  github:      chrisburnell
  twitter:     '@iamchrisburnell'
  employer:
    name: Squiz
    url:  https://www.squiz.net
    role: Front-End Developer

urls:
  buymeacoffee:       https://www.buymeacoffee.com/8mtx3EQfI
  codepen:            https://codepen.io/chrisburnell
  gist:               https://gist.github.com/chrisburnell
  github:             https://github.com/chrisburnell
  github_repo:        https://github.com/chrisburnell/chrisburnell.com
  lastfm:             https://last.fm/user/chrisburnell
  license:            https://www.gnu.org/licenses/gpl-3.0.txt
  londonwebstandards: https://londonwebstandards.org
  micropub:           https://micropub.chrisburnell.com
  microsub:           https://aperture.p3k.io/microsub/69
  notist:             https://noti.st/chrisburnell
  rss:                /feed.xml
  rss_articles:       /feed-articles.xml
  rss_bookmarks:      /feed-bookmarks.xml
  rss_notes:          /feed-notes.xml
  rss_pens:           /feed-pens.xml
  rss_talks:          /feed-talks.xml
  rss_recipes:        /feed-recipes.xml
  speakerdeck:        https://speakerdeck.com/chrisburnell
  stateofthebrowser:  https://stateofthebrowser.com
  spotify:            https://open.spotify.com/user/1128245857
  twitter:            https://twitter.com/iamchrisburnell
  webring:            https://xn--sr8hvo.ws/ðŸ’˜ðŸ‡¹ðŸ‡«

sitemap:
  changefreq: monthly
  priority:   0.5

codepen:
  page: details
  themes:
    default: 119
    tabfree: 8863

url:      https://chrisburnell.com
baseurl:  ''
shorturl: https://repc.co/

detach: false
host: 127.0.0.1
port: 9001

timezone: Europe/London
language: en

show_drafts: false
future: true
unpublished: false
incremental: true
destination: ./_site
permalink: /:categories/:title/

feed_limit: 25

emptyArray: []

collections:
  books:
    output: false

defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    layout: 'page'
- scope:
    path: '_drafts'
  values:
    layout: 'draft'
- scope:
    path: '_posts'
  values:
    layout: 'post'
    webmentions: true

exclude:
- CNAME
- CODE_OF_CONDUCT.md
- COMMIT_TEMPLATE.md
- CONTRIBUTING.md
- Gemfile
- gulpfile.babel.js
- ISSUE_TEMPLATE.md
- LICENSE
- node_modules
- package.json
- PULL_REQUEST_TEMPLATE.md
- README.md
- src
- vendor

plugins:
- jekyll-mentions
- jekyll-redirect-from

jekyll-mentions:
  base_url: https://twitter.com
