title: Chris Burnell
description: "Iâ€™m a Canadian user interface developer living in London, UK. This is where I write about and share my true passion: CSS architecture, design, innovation, standards, and user experience."
author: Chris Burnell
url: http://chrisburnell.com
employer: Squiz UK
employer_url: http://squiz.net
timezone: Europe/London

twitter_user: iamchrisburnell
twitter_url: http://twitter.com/iamchrisburnell
codepen_url: http://codepen.io/chrisburnell
lastfm_url: http://last.fm/user/chrisburnell

destination: ./_site
plugins: ./_plugins
layouts: ./_layouts

include: ['.htaccess']
exclude: []

future: false
permalink: /articles/:title
paginate: 10
paginate_path: 'page:num'

markdown: rdiscount
rdiscount:
  extensions: [smart]
markdown_ext: markdown,mkd,mkdn,md
