---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/posts/articles
  label: Articles
  create: documents
  match: "**/*"
- type: directory
  path: src/posts/notes
  label: Notes
  create: documents
  match: "**/*"
- type: directory
  path: src/posts/bookmarks
  label: Bookmarks
  create: documents
  match: "**/*"
upload_dir: images/content
public_path: "/images/content"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
